#cloud-config
local-hostname: ${name}
instance-id: ubuntu-${name}
network:
  version: 2
  ethernets:
    ens192:
      dhcp4: false
      addresses:
        - ${ipv4_address}/${ipv4_netmask}
      gateway4: ${ipv4_gateway}
      nameservers:
        search: [${domain}]
        addresses: ${dns_servers}
growpart:
  mode: auto
  devices: ['/dev/sda2']
  ignore_growroot_disabled: true
wait-on-network:
  ipv4: true
